language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - pio --version
    - pio update && pio upgrade && pio init

script:
    - pio run -t clean
    - pio ci --lib="src/" --project-conf=platformio.ini examples/dial/dial.ino
    - pio ci --lib="src/" --project-conf=platformio.ini examples/sms/sms.ino